// citiesAndDistricts.js

export const cities = [
    { label: 'ADANA', value: 'ADANA' },
    { label: 'ADIYAMAN', value: 'ADIYAMAN' },
    { label: 'AFYONKARAHİSAR', value: 'AFYONKARAHİSAR' },
    { label: 'AĞRI', value: 'AĞRI' },
    { label: 'AMASYA', value: 'AMASYA' },
    { label: 'ANKARA', value: 'ANKARA' },
    { label: 'ANTALYA', value: 'ANTALYA' },
    { label: 'ARTVİN', value: 'ARTVİN' },
    { label: 'AYDIN', value: 'AYDIN' },
    { label: 'BALIKESİR', value: 'BALIKESİR' },
    { label: 'BİLECİK', value: 'BİLECİK' },
    { label: 'BİNGÖL', value: 'BİNGÖL' },
    { label: 'BİTLİS', value: 'BİTLİS' },
    { label: 'BOLU', value: 'BOLU' },
    { label: 'BURDUR', value: 'BURDUR' },
    { label: 'BURSA', value: 'BURSA' },
    { label: 'ÇANAKKALE', value: 'ÇANAKKALE' },
    { label: 'ÇANKIRI', value: 'ÇANKIRI' },
    { label: 'ÇORUM', value: 'ÇORUM' },
    { label: 'DENİZLİ', value: 'DENİZLİ' },
    { label: 'DİYARBAKIR', value: 'DİYARBAKIR' },
    { label: 'EDİRNE', value: 'EDİRNE' },
    { label: 'ELAZIĞ', value: 'ELAZIĞ' },
    { label: 'ERZİNCAN', value: 'ERZİNCAN' },
    { label: 'ERZURUM', value: 'ERZURUM' },
    { label: 'ESKİŞEHİR', value: 'ESKİŞEHİR' },
    { label: 'GAZİANTEP', value: 'GAZİANTEP' },
    { label: 'GİRESUN', value: 'GİRESUN' },
    { label: 'GÜMÜŞHANE', value: 'GÜMÜŞHANE' },
    { label: 'HAKKARİ', value: 'HAKKARİ' },
    { label: 'HATAY', value: 'HATAY' },
    { label: 'ISPARTA', value: 'ISPARTA' },
    { label: 'MERSİN', value: 'MERSİN' },
    { label: 'İSTANBUL', value: 'İSTANBUL' },
    { label: 'İZMİR', value: 'İZMİR' },
    { label: 'KARS', value: 'KARS' },
    { label: 'KASTAMONU', value: 'KASTAMONU' },
    { label: 'KAYSERİ', value: 'KAYSERİ' },
    { label: 'KIRKLARELİ', value: 'KIRKLARELİ' },
    { label: 'KIRŞEHİR', value: 'KIRŞEHİR' },
    { label: 'KOCAELİ', value: 'KOCAELİ' },
    { label: 'KONYA', value: 'KONYA' },
    { label: 'KÜTAHYA', value: 'KÜTAHYA' },
    { label: 'MALATYA', value: 'MALATYA' },
    { label: 'MANİSA', value: 'MANİSA' },
    { label: 'KAHRAMANMARAŞ', value: 'KAHRAMANMARAŞ' },
    { label: 'MARDİN', value: 'MARDİN' },
    { label: 'MUĞLA', value: 'MUĞLA' },
    { label: 'MUŞ', value: 'MUŞ' },
    { label: 'NEVŞEHİR', value: 'NEVŞEHİR' },
    { label: 'NİĞDE', value: 'NİĞDE' },
    { label: 'ORDU', value: 'ORDU' },
    { label: 'RİZE', value: 'RİZE' },
    { label: 'SAKARYA', value: 'SAKARYA' },
    { label: 'SAMSUN', value: 'SAMSUN' },
    { label: 'SİİRT', value: 'SİİRT' },
    { label: 'SİNOP', value: 'SİNOP' },
    { label: 'SİVAS', value: 'SİVAS' },
    { label: 'TEKİRDAĞ', value: 'TEKİRDAĞ' },
    { label: 'TOKAT', value: 'TOKAT' },
    { label: 'TRABZON', value: 'TRABZON' },
    { label: 'TUNCELİ', value: 'TUNCELİ' },
    { label: 'ŞANLIURFA', value: 'ŞANLIURFA' },
    { label: 'UŞAK', value: 'UŞAK' },
    { label: 'VAN', value: 'VAN' },
    { label: 'YOZGAT', value: 'YOZGAT' },
    { label: 'ZONGULDAK', value: 'ZONGULDAK' },
    { label: 'AKSARAY', value: 'AKSARAY' },
    { label: 'BAYBURT', value: 'BAYBURT' },
    { label: 'KARAMAN', value: 'KARAMAN' },
    { label: 'KIRIKKALE', value: 'KIRIKKALE' },
    { label: 'BATMAN', value: 'BATMAN' },
    { label: 'ŞIRNAK', value: 'ŞIRNAK' },
    { label: 'BARTIN', value: 'BARTIN' },
    { label: 'ARDAHAN', value: 'ARDAHAN' },
    { label: 'IĞDIR', value: 'IĞDIR' },
    { label: 'YALOVA', value: 'YALOVA' },
    { label: 'KARABÜK', value: 'KARABÜK' },
    { label: 'KİLİS', value: 'KİLİS' },
    { label: 'OSMANİYE', value: 'OSMANİYE' },
    { label: 'DÜZCE', value: 'DÜZCE' },
  ];
  
  export const districts = {
    ADANA: [
      { label: 'ALADAĞ', value: 'ALADAĞ' },
      { label: 'CEYHAN', value: 'CEYHAN' },
      { label: 'ÇUKUROVA', value: 'ÇUKUROVA' },
      { label: 'FEKE', value: 'FEKE' },
      { label: 'İMAMOĞLU', value: 'İMAMOĞLU' },
      { label: 'KARAİSALI', value: 'KARAİSALI' },
      { label: 'KARATAŞ', value: 'KARATAŞ' },
      { label: 'KOZAN', value: 'KOZAN' },
      { label: 'POZANTI', value: 'POZANTI' },
      { label: 'SAİMBEYLİ', value: 'SAİMBEYLİ' },
      { label: 'SARIÇAM', value: 'SARIÇAM' },
      { label: 'SEYHAN', value: 'SEYHAN' },
      { label: 'TUFANBEYLİ', value: 'TUFANBEYLİ' },
      { label: 'YUMURTALIK', value: 'YUMURTALIK' },
      { label: 'YÜREĞİR', value: 'YÜREĞİR' },
    ],
    ADIYAMAN: [
      { label: 'BESNİ', value: 'BESNİ' },
      { label: 'ÇELİKHAN', value: 'ÇELİKHAN' },
      { label: 'GERGER', value: 'GERGER' },
      { label: 'GÖLBAŞI', value: 'GÖLBAŞI' },
      { label: 'KAHTA', value: 'KAHTA' },
      { label: 'MERKEZ', value: 'MERKEZ' },
      { label: 'SAMSAT', value: 'SAMSAT' },
      { label: 'SİNCİK', value: 'SİNCİK' },
      { label: 'TUT', value: 'TUT' },
    ],
    AFYONKARAHİSAR: [
      { label: 'BAŞMAKÇI', value: 'BAŞMAKÇI' },
      { label: 'BAYAT', value: 'BAYAT' },
      { label: 'BOLVADİN', value: 'BOLVADİN' },
      { label: 'ÇAY', value: 'ÇAY' },
      { label: 'ÇOBANLAR', value: 'ÇOBANLAR' },
      { label: 'DAZKIRI', value: 'DAZKIRI' },
      { label: 'DİNAR', value: 'DİNAR' },
      { label: 'EMİRDAĞ', value: 'EMİRDAĞ' },
      { label: 'EVCİLER', value: 'EVCİLER' },
      { label: 'HOCALAR', value: 'HOCALAR' },
      { label: 'İHSANİYE', value: 'İHSANİYE' },
      { label: 'İSCEHİSAR', value: 'İSCEHİSAR' },
      { label: 'KIZILÖREN', value: 'KIZILÖREN' },
      { label: 'MERKEZ', value: 'MERKEZ' },
      { label: 'SANDIKLI', value: 'SANDIKLI' },
      { label: 'SİNANPAŞA', value: 'SİNANPAŞA' },
      { label: 'SULTANDAĞI', value: 'SULTANDAĞI' },
      { label: 'ŞUHUT', value: 'ŞUHUT' },
    ],
    AĞRI: [
      { label: 'DİYADİN', value: 'DİYADİN' },
      { label: 'DOĞUBAYAZIT', value: 'DOĞUBAYAZIT' },
      { label: 'ELEŞKİRT', value: 'ELEŞKİRT' },
      { label: 'HAMUR', value: 'HAMUR' },
      { label: 'MERKEZ', value: 'MERKEZ' },
      { label: 'PATNOS', value: 'PATNOS' },
      { label: 'TAŞLIÇAY', value: 'TAŞLIÇAY' },
      { label: 'TUTAK', value: 'TUTAK' },
    ],
    AMASYA: [
      { label: 'GÖYNÜCEK', value: 'GÖYNÜCEK' },
      { label: 'GÜMÜŞHACIKÖY', value: 'GÜMÜŞHACIKÖY' },
      { label: 'MERZİFON', value: 'MERZİFON' },
      { label: 'MERKEZ', value: 'MERKEZ' },
      { label: 'SULUOVA', value: 'SULUOVA' },
      { label: 'TAŞOVA', value: 'TAŞOVA' },
    ],
    ANKARA: [
      { label: 'AKYURT', value: 'AKYURT' },
      { label: 'ALTINDAĞ', value: 'ALTINDAĞ' },
      { label: 'AYAŞ', value: 'AYAŞ' },
      { label: 'BALA', value: 'BALA' },
      { label: 'BEYPAZARI', value: 'BEYPAZARI' },
      { label: 'ÇAMLIDERE', value: 'ÇAMLIDERE' },
      { label: 'ÇANKAYA', value: 'ÇANKAYA' },
      { label: 'ÇUBUK', value: 'ÇUBUK' },
      { label: 'ELMADAĞ', value: 'ELMADAĞ' },
      { label: 'ETİMESGUT', value: 'ETİMESGUT' },
      { label: 'EVREN', value: 'EVREN' },
      { label: 'GÖLBAŞI', value: 'GÖLBAŞI' },
      { label: 'GÜDÜL', value: 'GÜDÜL' },
      { label: 'HAYMANA', value: 'HAYMANA' },
      { label: 'KALECİK', value: 'KALECİK' },
      { label: 'KAZAN', value: 'KAZAN' },
      { label: 'KEÇİÖREN', value: 'KEÇİÖREN' },
      { label: 'KIZILCAHAMAM', value: 'KIZILCAHAMAM' },
      { label: 'MAMAK', value: 'MAMAK' },
      { label: 'NALLIHAN', value: 'NALLIHAN' },
      { label: 'POLATLI', value: 'POLATLI' },
      { label: 'PURSAKLAR', value: 'PURSAKLAR' },
      { label: 'ŞEREFLİKOÇHİSAR', value: 'ŞEREFLİKOÇHİSAR' },
      { label: 'SİNCAN', value: 'SİNCAN' },
      { label: 'YENİMAHALLE', value: 'YENİMAHALLE' },
    ],
    ANTALYA: [
      { label: 'AKSEKİ', value: 'AKSEKİ' },
      { label: 'AKSU', value: 'AKSU' },
      { label: 'ALANYA', value: 'ALANYA' },
      { label: 'DEMRE', value: 'DEMRE' },
      { label: 'DÖŞEMEALTI', value: 'DÖŞEMEALTI' },
      { label: 'ELMALI', value: 'ELMALI' },
      { label: 'FİNİKE', value: 'FİNİKE' },
      { label: 'GAZİPAŞA', value: 'GAZİPAŞA' },
      { label: 'GÜNDOĞMUŞ', value: 'GÜNDOĞMUŞ' },
      { label: 'İBRADI', value: 'İBRADI' },
      { label: 'KAŞ', value: 'KAŞ' },
      { label: 'KEMER', value: 'KEMER' },
      { label: 'KEPEZ', value: 'KEPEZ' },
      { label: 'KONYAALTI', value: 'KONYAALTI' },
      { label: 'KORKUTELİ', value: 'KORKUTELİ' },
      { label: 'KUMLUCA', value: 'KUMLUCA' },
      { label: 'MANAVGAT', value: 'MANAVGAT' },
      { label: 'MURATPAŞA', value: 'MURATPAŞA' },
      { label: 'SERİK', value: 'SERİK' },
    ],
    ARDAHAN: [
      { label: 'ÇILDIR', value: 'ÇILDIR' },
      { label: 'DAMAL', value: 'DAMAL' },
      { label: 'GÖLE', value: 'GÖLE' },
      { label: 'HANAK', value: 'HANAK' },
      { label: 'MERKEZ', value: 'MERKEZ' },
      { label: 'POSOF', value: 'POSOF' },
    ],
    ARTVİN: [
      { label: 'ARDANUÇ', value: 'ARDANUÇ' },
      { label: 'ARHAVİ', value: 'ARHAVİ' },
      { label: 'BORÇKA', value: 'BORÇKA' },
      { label: 'HOPA', value: 'HOPA' },
      { label: 'KEMALPAŞA', value: 'KEMALPAŞA' },
      { label: 'MERKEZ', value: 'MERKEZ' },
      { label: 'MURGUL', value: 'MURGUL' },
      { label: 'ŞAVŞAT', value: 'ŞAVŞAT' },
      { label: 'YUSUFELİ', value: 'YUSUFELİ' },
    ],
    AYDIN: [
      { label: 'BOZDOĞAN', value: 'BOZDOĞAN' },
      { label: 'BUHARKENT', value: 'BUHARKENT' },
      { label: 'ÇİNE', value: 'ÇİNE' },
      { label: 'DİDİM', value: 'DİDİM' },
      { label: 'EFELER', value: 'EFELER' },
      { label: 'GERMENCİK', value: 'GERMENCİK' },
      { label: 'İNCİRLİOVA', value: 'İNCİRLİOVA' },
      { label: 'KARACASU', value: 'KARACASU' },
      { label: 'KARPUZLU', value: 'KARPUZLU' },
      { label: 'KOÇARLI', value: 'KOÇARLI' },
      { label: 'KÖŞK', value: 'KÖŞK' },
      { label: 'KUŞADASI', value: 'KUŞADASI' },
      { label: 'KUYUCAK', value: 'KUYUCAK' },
      { label: 'NAZİLLİ', value: 'NAZİLLİ' },
      { label: 'SÖKE', value: 'SÖKE' },
      { label: 'SULTANHİSAR', value: 'SULTANHİSAR' },
      { label: 'YENİPAZAR', value: 'YENİPAZAR' },
    ],
    BALIKESİR: [
      { label: 'ALTIEYLÜL', value: 'ALTIEYLÜL' },
      { label: 'AYVALIK', value: 'AYVALIK' },
      { label: 'BALYA', value: 'BALYA' },
      { label: 'BANDIRMA', value: 'BANDIRMA' },
      { label: 'BİGADİÇ', value: 'BİGADİÇ' },
      { label: 'BURHANİYE', value: 'BURHANİYE' },
      { label: 'DURSUNBEY', value: 'DURSUNBEY' },
      { label: 'EDREMİT', value: 'EDREMİT' },
      { label: 'ERDEK', value: 'ERDEK' },
      { label: 'GÖMEÇ', value: 'GÖMEÇ' },
      { label: 'GÖNEN', value: 'GÖNEN' },
      { label: 'HAVRAN', value: 'HAVRAN' },
      { label: 'İVRİNDİ', value: 'İVRİNDİ' },
      { label: 'KARESİ', value: 'KARESİ' },
      { label: 'KEPSUT', value: 'KEPSUT' },
      { label: 'MANYAS', value: 'MANYAS' },
      { label: 'MARMARA', value: 'MARMARA' },
      { label: 'SAVAŞTEPE', value: 'SAVAŞTEPE' },
      { label: 'SINDIRGI', value: 'SINDIRGI' },
      { label: 'SUSURLUK', value: 'SUSURLUK' },
    ],
    BARTIN: [
      { label: 'AMASRA', value: 'AMASRA' },
      { label: 'KURUCAŞİLE', value: 'KURUCAŞİLE' },
      { label: 'MERKEZ', value: 'MERKEZ' },
      { label: 'ULUS', value: 'ULUS' },
    ],
    BATMAN: [
      { label: 'BEŞİRİ', value: 'BEŞİRİ' },
      { label: 'GERCÜŞ', value: 'GERCÜŞ' },
      { label: 'HASANKEYF', value: 'HASANKEYF' },
      { label: 'KOZLUK', value: 'KOZLUK' },
      { label: 'MERKEZ', value: 'MERKEZ' },
      { label: 'SASON', value: 'SASON' },
    ],
    BAYBURT: [
      { label: 'AYDINTEPE', value: 'AYDINTEPE' },
      { label: 'DEMİRÖZÜ', value: 'DEMİRÖZÜ' },
      { label: 'MERKEZ', value: 'MERKEZ' },
    ],
    BİLECİK: [
      { label: 'BOZÜYÜK', value: 'BOZÜYÜK' },
      { label: 'GÖLPAZARI', value: 'GÖLPAZARI' },
      { label: 'İNHİSAR', value: 'İNHİSAR' },
      { label: 'MERKEZ', value: 'MERKEZ' },
      { label: 'OSMANELİ', value: 'OSMANELİ' },
      { label: 'PAZARYERİ', value: 'PAZARYERİ' },
      { label: 'SÖĞÜT', value: 'SÖĞÜT' },
      { label: 'YENİPAZAR', value: 'YENİPAZAR' },
    ],
    BİNGÖL: [
      { label: 'ADAKLI', value: 'ADAKLI' },
      { label: 'GENÇ', value: 'GENÇ' },
      { label: 'KARLIOVA', value: 'KARLIOVA' },
      { label: 'KİĞI', value: 'KİĞI' },
      { label: 'MERKEZ', value: 'MERKEZ' },
      { label: 'SOLHAN', value: 'SOLHAN' },
      { label: 'YAYLADERE', value: 'YAYLADERE' },
      { label: 'YEDİSU', value: 'YEDİSU' },
    ],
    BİTLİS: [
      { label: 'ADİLCEVAZ', value: 'ADİLCEVAZ' },
      { label: 'AHLAT', value: 'AHLAT' },
      { label: 'GÜROYMAK', value: 'GÜROYMAK' },
      { label: 'HİZAN', value: 'HİZAN' },
      { label: 'MERKEZ', value: 'MERKEZ' },
      { label: 'MUTKİ', value: 'MUTKİ' },
      { label: 'TATVAN', value: 'TATVAN' },
    ],
    BOLU: [
      { label: 'DÖRTDİVAN', value: 'DÖRTDİVAN' },
      { label: 'GEREDE', value: 'GEREDE' },
      { label: 'GÖYNÜK', value: 'GÖYNÜK' },
      { label: 'KIBRISCIK', value: 'KIBRISCIK' },
      { label: 'MENGEN', value: 'MENGEN' },
      { label: 'MERKEZ', value: 'MERKEZ' },
      { label: 'MUDURNU', value: 'MUDURNU' },
      { label: 'SEBEN', value: 'SEBEN' },
      { label: 'YENİÇAĞA', value: 'YENİÇAĞA' },
    ],
    BURDUR: [
      { label: 'AĞLASUN', value: 'AĞLASUN' },
      { label: 'ALTINYAYLA', value: 'ALTINYAYLA' },
      { label: 'BUCAK', value: 'BUCAK' },
      { label: 'ÇAVDIR', value: 'ÇAVDIR' },
      { label: 'ÇELTİKÇİ', value: 'ÇELTİKÇİ' },
      { label: 'GÖLHİSAR', value: 'GÖLHİSAR' },
      { label: 'KARAMANLI', value: 'KARAMANLI' },
      { label: 'KEMER', value: 'KEMER' },
      { label: 'MERKEZ', value: 'MERKEZ' },
      { label: 'TEFENNİ', value: 'TEFENNİ' },
      { label: 'YEŞİLOVA', value: 'YEŞİLOVA' },
    ],
    BURSA: [
      { label: 'BÜYÜKORHAN', value: 'BÜYÜKORHAN' },
      { label: 'GEMLİK', value: 'GEMLİK' },
      { label: 'GÜRSU', value: 'GÜRSU' },
      { label: 'HARMANCIK', value: 'HARMANCIK' },
      { label: 'İNEGÖL', value: 'İNEGÖL' },
      { label: 'İZNİK', value: 'İZNİK' },
      { label: 'KARACABEY', value: 'KARACABEY' },
      { label: 'KELES', value: 'KELES' },
      { label: 'KESTEL', value: 'KESTEL' },
      { label: 'MUDANYA', value: 'MUDANYA' },
      { label: 'MUSTAFAKEMALPAŞA', value: 'MUSTAFAKEMALPAŞA' },
      { label: 'NİLÜFER', value: 'NİLÜFER' },
      { label: 'ORHANELİ', value: 'ORHANELİ' },
      { label: 'ORHANGAZİ', value: 'ORHANGAZİ' },
      { label: 'OSMANGAZİ', value: 'OSMANGAZİ' },
      { label: 'YENİŞEHİR', value: 'YENİŞEHİR' },
      { label: 'YILDIRIM', value: 'YILDIRIM' },
    ],
    ÇANAKKALE: [
      { label: 'AYVACIK', value: 'AYVACIK' },
      { label: 'BAYRAMİÇ', value: 'BAYRAMİÇ' },
      { label: 'BİGA', value: 'BİGA' },
      { label: 'BOZCAADA', value: 'BOZCAADA' },
      { label: 'ÇAN', value: 'ÇAN' },
      { label: 'ECEABAT', value: 'ECEABAT' },
      { label: 'EZİNE', value: 'EZİNE' },
      { label: 'GELİBOLU', value: 'GELİBOLU' },
      { label: 'GÖKÇEADA', value: 'GÖKÇEADA' },
      { label: 'LAPSEKİ', value: 'LAPSEKİ' },
      { label: 'MERKEZ', value: 'MERKEZ' },
      { label: 'YENİCE', value: 'YENİCE' },
    ],
    ÇANKIRI: [
      { label: 'ATKARACALAR', value: 'ATKARACALAR' },
      { label: 'BAYRAMÖREN', value: 'BAYRAMÖREN' },
      { label: 'ÇERKEŞ', value: 'ÇERKEŞ' },
      { label: 'ELDİVAN', value: 'ELDİVAN' },
      { label: 'ILGAZ', value: 'ILGAZ' },
      { label: 'KIZILIRMAK', value: 'KIZILIRMAK' },
      { label: 'KORGUN', value: 'KORGUN' },
      { label: 'KURŞUNLU', value: 'KURŞUNLU' },
      { label: 'MERKEZ', value: 'MERKEZ' },
      { label: 'ORTA', value: 'ORTA' },
      { label: 'ŞABANÖZÜ', value: 'ŞABANÖZÜ' },
      { label: 'YAPRAKLI', value: 'YAPRAKLI' },
    ],
    ÇORUM: [
        { label: 'ALACA', value: 'ALACA' },
        { label: 'BAYAT', value: 'BAYAT' },
        { label: 'BOĞAZKALE', value: 'BOĞAZKALE' },
        { label: 'DODURGA', value: 'DODURGA' },
        { label: 'İSKİLİP', value: 'İSKİLİ'},
    ],
    DENİZLİ: [
        { label: 'ACIPAYAM', value: 'ACIPAYAM' },
        { label: 'BABADAĞ', value: 'BABADAĞ' },
        { label: 'BAKLAN', value: 'BAKLAN' },
        { label: 'BEKİLLİ', value: 'BEKİLLİ' },
        { label: 'BEYAĞAÇ', value: 'BEYAĞAÇ' },
        { label: 'BOZKURT', value: 'BOZKURT' },
        { label: 'BULDAN', value: 'BULDAN' },
        { label: 'ÇAL', value: 'ÇAL' },
        { label: 'ÇAMELİ', value: 'ÇAMELİ' },
        { label: 'ÇARDAK', value: 'ÇARDAK' },
        { label: 'ÇİVRİL', value: 'ÇİVRİL' },
        { label: 'GÜNEY', value: 'GÜNEY' },
        { label: 'HONAZ', value: 'HONAZ' },
        { label: 'KALE', value: 'KALE' },
        { label: 'MERKEZEFENDİ', value: 'MERKEZEFENDİ' },
        { label: 'PAMUKKALE', value: 'PAMUKKALE' },
        { label: 'SARAYKÖY', value: 'SARAYKÖY' },
        { label: 'SERİNHİSAR', value: 'SERİNHİSAR' },
        { label: 'TAVAS', value: 'TAVAS' },
      ],
      DİYARBAKIR: [
        { label: 'BAĞLAR', value: 'BAĞLAR' },
        { label: 'BİSMİL', value: 'BİSMİL' },
        { label: 'ÇERMİK', value: 'ÇERMİK' },
        { label: 'ÇINAR', value: 'ÇINAR' },
        { label: 'ÇÜNGÜŞ', value: 'ÇÜNGÜŞ' },
        { label: 'DİCLE', value: 'DİCLE' },
        { label: 'EĞİL', value: 'EĞİL' },
        { label: 'ERGANİ', value: 'ERGANİ' },
        { label: 'HANİ', value: 'HANİ' },
        { label: 'HAZRO', value: 'HAZRO' },
        { label: 'KAYAPINAR', value: 'KAYAPINAR' },
        { label: 'KOCAKÖY', value: 'KOCAKÖY' },
        { label: 'KULP', value: 'KULP' },
        { label: 'LİCE', value: 'LİCE' },
        { label: 'SİLVAN', value: 'SİLVAN' },
        { label: 'SUR', value: 'SUR' },
        { label: 'YENİŞEHİR', value: 'YENİŞEHİR' },
      ],
      DÜZCE: [
        { label: 'AKÇAKOCA', value: 'AKÇAKOCA' },
        { label: 'CUMAYERİ', value: 'CUMAYERİ' },
        { label: 'ÇİLİMLİ', value: 'ÇİLİMLİ' },
        { label: 'GÖLYAKA', value: 'GÖLYAKA' },
        { label: 'GÜMÜŞOVA', value: 'GÜMÜŞOVA' },
        { label: 'KAYNAŞLI', value: 'KAYNAŞLI' },
        { label: 'MERKEZ', value: 'MERKEZ' },
        { label: 'YIĞILCA', value: 'YIĞILCA' },
      ],
      EDİRNE: [
        { label: 'ENEZ', value: 'ENEZ' },
        { label: 'HAVSA', value: 'HAVSA' },
        { label: 'İPSALA', value: 'İPSALA' },
        { label: 'KEŞAN', value: 'KEŞAN' },
        { label: 'LALAPAŞA', value: 'LALAPAŞA' },
        { label: 'MERİÇ', value: 'MERİÇ' },
        { label: 'MERKEZ', value: 'MERKEZ' },
        { label: 'SÜLOĞLU', value: 'SÜLOĞLU' },
        { label: 'UZUNKÖPRÜ', value: 'UZUNKÖPRÜ' },
      ],
      ELAZIĞ: [
        { label: 'AĞIN', value: 'AĞIN' },
        { label: 'ALACAKAYA', value: 'ALACAKAYA' },
        { label: 'ARICAK', value: 'ARICAK' },
        { label: 'BASKİL', value: 'BASKİL' },
        { label: 'KARAKOÇAN', value: 'KARAKOÇAN' },
        { label: 'KEBAN', value: 'KEBAN' },
        { label: 'KOVANCILAR', value: 'KOVANCILAR' },
        { label: 'MADEN', value: 'MADEN' },
        { label: 'MERKEZ', value: 'MERKEZ' },
        { label: 'PALU', value: 'PALU' },
        { label: 'SİVRİCE', value: 'SİVRİCE' },
      ],
      ERZİNCAN: [
        { label: 'ÇAYIRLI', value: 'ÇAYIRLI' },
        { label: 'İLİÇ', value: 'İLİÇ' },
        { label: 'KEMAH', value: 'KEMAH' },
        { label: 'KEMALİYE', value: 'KEMALİYE' },
        { label: 'MERKEZ', value: 'MERKEZ' },
        { label: 'OTLUKBELİ', value: 'OTLUKBELİ' },
        { label: 'REFAHİYE', value: 'REFAHİYE' },
        { label: 'TERCAN', value: 'TERCAN' },
        { label: 'ÜZÜMLÜ', value: 'ÜZÜMLÜ' },
      ],
      ERZURUM: [
        { label: 'AŞKALE', value: 'AŞKALE' },
        { label: 'ÇAT', value: 'ÇAT' },
        { label: 'HINIS', value: 'HINIS' },
        { label: 'HORASAN', value: 'HORASAN' },
        { label: 'İSPİR', value: 'İSPİR' },
        { label: 'KARAÇOBAN', value: 'KARAÇOBAN' },
        { label: 'KARAYAZI', value: 'KARAYAZI' },
        { label: 'KÖPRÜKÖY', value: 'KÖPRÜKÖY' },
        { label: 'NARMAN', value: 'NARMAN' },
        { label: 'OLTU', value: 'OLTU' },
        { label: 'OLUR', value: 'OLUR' },
        { label: 'PALANDÖKEN', value: 'PALANDÖKEN' },
        { label: 'PASİNLER', value: 'PASİNLER' },
        { label: 'PAZARYOLU', value: 'PAZARYOLU' },
        { label: 'ŞENKAYA', value: 'ŞENKAYA' },
        { label: 'TEKMAN', value: 'TEKMAN' },
        { label: 'TORTUM', value: 'TORTUM' },
        { label: 'UZUNDERE', value: 'UZUNDERE' },
        { label: 'YAKUTİYE', value: 'YAKUTİYE' },
      ],
      ESKİŞEHİR: [
        { label: 'ALPU', value: 'ALPU' },
        { label: 'BEYLİKOVA', value: 'BEYLİKOVA' },
        { label: 'ÇİFTELER', value: 'ÇİFTELER' },
        { label: 'GÜNYÜZÜ', value: 'GÜNYÜZÜ' },
        { label: 'HAN', value: 'HAN' },
        { label: 'İNÖNÜ', value: 'İNÖNÜ' },
        { label: 'MAHMUDİYE', value: 'MAHMUDİYE' },
        { label: 'MİHALGAZİ', value: 'MİHALGAZİ' },
        { label: 'MİHALIÇÇIK', value: 'MİHALIÇÇIK' },
        { label: 'ODUNPAZARI', value: 'ODUNPAZARI' },
        { label: 'SARICAKAYA', value: 'SARICAKAYA' },
        { label: 'SEYİTGAZİ', value: 'SEYİTGAZİ' },
        { label: 'SİVRİHİSAR', value: 'SİVRİHİSAR' },
        { label: 'TEPEBAŞI', value: 'TEPEBAŞI' },
      ],
      GAZİANTEP: [
        { label: 'ARABAN', value: 'ARABAN' },
        { label: 'İSLAHİYE', value: 'İSLAHİYE' },
        { label: 'KARKAMIŞ', value: 'KARKAMIŞ' },
        { label: 'NİZİP', value: 'NİZİP' },
        { label: 'NURDAĞI', value: 'NURDAĞI' },
        { label: 'OĞUZELİ', value: 'OĞUZELİ' },
        { label: 'ŞAHİNBEY', value: 'ŞAHİNBEY' },
        { label: 'ŞEHİTKAMİL', value: 'ŞEHİTKAMİL' },
        { label: 'YAVUZELİ', value: 'YAVUZELİ' },
      ],
      GİRESUN: [
        { label: 'ALUCRA', value: 'ALUCRA' },
        { label: 'BULANCAK', value: 'BULANCAK' },
        { label: 'ÇAMOLUK', value: 'ÇAMOLUK' },
        { label: 'ÇANAKÇI', value: 'ÇANAKÇI' },
        { label: 'DERELİ', value: 'DERELİ' },
        { label: 'DOĞANKENT', value: 'DOĞANKENT' },
        { label: 'ESPİYE', value: 'ESPİYE' },
        { label: 'EYNESİL', value: 'EYNESİL' },
        { label: 'GÖRELE', value: 'GÖRELE' },
        { label: 'GÜCE', value: 'GÜCE' },
        { label: 'KEŞAP', value: 'KEŞAP' },
        { label: 'MERKEZ', value: 'MERKEZ' },
        { label: 'PİRAZİZ', value: 'PİRAZİZ' },
        { label: 'ŞEBİNKARAHİSAR', value: 'ŞEBİNKARAHİSAR' },
        { label: 'TİREBOLU', value: 'TİREBOLU' },
        { label: 'YAĞLIDERE', value: 'YAĞLIDERE' },
      ],
      GÜMÜŞHANE: [
        { label: 'KELKİT', value: 'KELKİT' },
        { label: 'KÖSE', value: 'KÖSE' },
        { label: 'KÜRTÜN', value: 'KÜRTÜN' },
        { label: 'MERKEZ', value: 'MERKEZ' },
        { label: 'ŞİRAN', value: 'ŞİRAN' },
        { label: 'TORUL', value: 'TORUL' },
      ],
      HAKKARİ: [
        { label: 'ÇUKURCA', value: 'ÇUKURCA' },
        { label: 'DERECİK', value: 'DERECİK' },
        { label: 'MERKEZ', value: 'MERKEZ' },
        { label: 'ŞEMDİNLİ', value: 'ŞEMDİNLİ' },
        { label: 'YÜKSEKOVA', value: 'YÜKSEKOVA' },
      ],
      HATAY: [
        { label: 'ALTINÖZÜ', value: 'ALTINÖZÜ' },
        { label: 'ANTAKYA', value: 'ANTAKYA' },
        { label: 'ARSUZ', value: 'ARSUZ' },
        { label: 'BELEN', value: 'BELEN' },
        { label: 'DEFNE', value: 'DEFNE' },
        { label: 'DÖRTYOL', value: 'DÖRTYOL' },
        { label: 'ERZİN', value: 'ERZİN' },
        { label: 'HASSA', value: 'HASSA' },
        { label: 'İSKENDERUN', value: 'İSKENDERUN' },
        { label: 'KIRIKHAN', value: 'KIRIKHAN' },
        { label: 'KUMLU', value: 'KUMLU' },
        { label: 'PAYAS', value: 'PAYAS' },
        { label: 'REYHANLI', value: 'REYHANLI' },
        { label: 'SAMANDAĞ', value: 'SAMANDAĞ' },
        { label: 'YAYLADAĞI', value: 'YAYLADAĞI' },
      ],
      IĞDIR: [
        { label: 'ARALIK', value: 'ARALIK' },
        { label: 'KARAKOYUNLU', value: 'KARAKOYUNLU' },
        { label: 'MERKEZ', value: 'MERKEZ' },
        { label: 'TUZLUCA', value: 'TUZLUCA' },
      ],
      ISPARTA: [
        { label: 'AKSU', value: 'AKSU' },
        { label: 'ATABEY', value: 'ATABEY' },
        { label: 'EĞİRDİR', value: 'EĞİRDİR' },
        { label: 'GELENDOST', value: 'GELENDOST' },
        { label: 'GÖNEN', value: 'GÖNEN' },
        { label: 'KEÇİBORLU', value: 'KEÇİBORLU' },
        { label: 'MERKEZ', value: 'MERKEZ' },
        { label: 'SENİRKENT', value: 'SENİRKENT' },
        { label: 'SÜTÇÜLER', value: 'SÜTÇÜLER' },
        { label: 'ŞARKİKARAAĞAÇ', value: 'ŞARKİKARAAĞAÇ' },
        { label: 'ULUBORLU', value: 'ULUBORLU' },
        { label: 'YALVAÇ', value: 'YALVAÇ' },
        { label: 'YENİŞARBADEMLİ', value: 'YENİŞARBADEMLİ' },
      ],
      MERSİN: [
        { label: 'AKDENİZ', value: 'AKDENİZ' },
        { label: 'ANAMUR', value: 'ANAMUR' },
        { label: 'AYDINCIK', value: 'AYDINCIK' },
        { label: 'BOZYAZI', value: 'BOZYAZI' },
        { label: 'ÇAMLIYAYLA', value: 'ÇAMLIYAYLA' },
        { label: 'ERDEMLİ', value: 'ERDEMLİ' },
        { label: 'GÜLNAR', value: 'GÜLNAR' },
        { label: 'MEZİTLİ', value: 'MEZİTLİ' },
        { label: 'MUT', value: 'MUT' },
        { label: 'SİLİFKE', value: 'SİLİFKE' },
        { label: 'TARSUS', value: 'TARSUS' },
        { label: 'TOROSLAR', value: 'TOROSLAR' },
        { label: 'YENİŞEHİR', value: 'YENİŞEHİR' },
      ],
}